version: '3.8'

services:
    rabbitmq:
        container_name: rabbitmq-email
        hostname: rabbitmq
        image: rabbitmq:3.11-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672

    postgres:
        container_name: postgresql
        image: 'postgres:latest'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432